name: Hyundai Card Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Restore client_secret.json
        env:
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
        run: echo "$CLIENT_SECRET_JSON" > client_secret.json
      
      - name: Restore token.pickle
        env:
          TOKEN_PICKLE_B64: ${{ secrets.TOKEN_PICKLE_B64 }}
        run: echo "$TOKEN_PICKLE_B64" | base64 -d > token.pickle
      
      - name: Run Hyundai Card Automation
        run: python hyundai_automation.py
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: hyundai_automation.log
          retention-days: 7
