name: Hyundai Card Automation

on:
  schedule:
    - cron: '0 2 * * *'  # 매일 UTC 2:00 (KST 11:00)
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: gapho-park/hyundai-automation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies and fix Chrome
        run: |
          sudo apt-get update
          
          # Chromium (snap 버전) 설치
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
          # Chromium snap 바이너리를 /usr/bin/google-chrome으로 symlink
          sudo ln -sf /snap/chromium/current/usr/bin/chromium /usr/bin/google-chrome
          
          # ChromeDriver도 snap 버전으로 symlink
          sudo ln -sf /snap/chromium/current/usr/bin/chromedriver /usr/bin/chromedriver
          
          # 버전 확인
          /snap/chromium/current/usr/bin/chromium --version
          /snap/chromium/current/usr/bin/chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager

      - name: Create credentials from secrets
        run: |
          echo "${{ secrets.CLIENT_SECRET_JSON }}" > client_secret.json
          echo "${{ secrets.TOKEN_PICKLE_B64 }}" | base64 -d > token.pickle

      - name: Run automation
        env:
          CHROME_BIN: /usr/bin/google-chrome
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
          CI: true
        run: |
          python hyundai_automation.py

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: |
            hyundai_automation.log
            *.html
          retention-days: 7

      - name: Upload results on success
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: automation-results
          path: |
            *.csv
            *.xlsx
          retention-days: 30
